let N = parseFloat(prompt("Enter a number"));
let W = parseFloat(prompt("Enter a number"));
let L = parseFloat(prompt("Enter a number"));
let M = parseFloat(prompt("Enter a number"));
let O = parseFloat(prompt("Enter a number"));
let S = N*N;
let SP = M*O;
let PP = S - SP;
let SPP = W*L;
console.log(PP/SPP);
console.log((PP/SPP)*0.2);
